### ISSUE TITLE
Css problem

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/ckeditor_addon#3]
![1](https://cloud.githubusercontent.com/assets/13515302/14213520/118f4210-f841-11e5-87cd-34d9552275ba.png)

Back to normal view formatting is broken:

![2](https://cloud.githubusercontent.com/assets/13515302/14213535/20609e7e-f841-11e5-9a85-4a8e0f18b9fc.png)

**Comment by ghost** [comment]
Thanks for the report !
I use only firefox, and never use full screen mode, so I had a hard debugging party…
Finally, the cause was my fancy autogrow plugin, which should not act in full screen mode !

Fixed.

**Comment by ghost** [comment]
BTW, I wrote this autogrowcustom plugin precisely to avoid usage of full screen mode (which breaks the field layout).
What did not work for you, which made you enter full screen mode ?

**Comment by bd0bd** [comment]
Thank you!

I use Chrome, Firefox, Opera, IE, Safari, Android.

Often I use small notebook with resolution 1024 x 600 and it is much more comfortable to use full screen mode when editing content.
